### ISSUE TITLE
error when trying to authenticate

### ISSUE THREAD

**Issue by DrMagPie** [hunvreus/jekyllplus#12]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/23652900/96852840-51ffc800-1462-11eb-81c0-e6bc407c5791.png">

Please note that I was trying to login on to https://cms.jekyllplus.com/login
but got this url https://micro-github-ttreyqtgxf.now.sh/login?scope=repo

it seams to be hardcoded here 
https://github.com/Wiredcraft/jekyllplus/blob/master/src/components/Login.vue#L15

this seams to be hardcoded here
https://github.com/Wiredcraft/jekyllplus/blob/7e33812c9ad7eb60de44ef003b84f9e88fc90861/src/components/Login.vue#L15

**Comment by hunvreus** [comment]
@DrMagPie Sorry for not answering this request.

I'm working on a completely revamped version that runs on Cloudflare Workers. It should be ready by end of this month. Let me know if you'd like to give it a spin.

**Comment by hunvreus** [comment]
@DrMagPie I suggest you check Pages CMS instead:

- Official website: https://pagescms.org/
- GitHub repo: https://github.com/pages-cms/pages-cms

It does everything Jekyll+ did and a lot more.
